title: Test Page
author: Friedrich Lorenz
email: Friedrich.Lorenz@wiwi.uni-muenster.de
description: > # this means to ignore newlines until "baseurl:"
  Homepage of Friedrich Lorenz.
markdown: kramdown
